# These are supported funding model platforms

github: [eliasbenb]
patreon:
open_collective:
ko_fi: eliasbenb
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
custom: ["https://paypal.me/eliasbenb"]
